domain: ERP

tables:
  menu_items:
    raw_path: data/raw/erp/menu_items.csv.gz
    order_items_path: data/raw/crm/order_items.csv.gz
    silver_path: data/silver/erp/menu_items.parquet
    dq_threshold: 5

  restaurants:
    raw_path: data/raw/erp/restaurants.csv.gz
    silver_path: data/silver/erp/restaurants.parquet
    dq_threshold: 5

  delivery_partners:
    raw_path: data/raw/erp/delivery_partners.csv.gz
    silver_path: data/silver/erp/delivery_partners.parquet
    dq_threshold: 5

  employees:
    raw_path: data/raw/erp/employees.csv.gz
    restaurants_path: data/silver/erp/restaurants.parquet
    silver_path: data/silver/erp/employees.parquet
    dq_threshold: 5

  kitchen_logs:
    raw_path: data/raw/erp/kitchen_logs.csv.gz
    employees_path: data/silver/erp/employees.parquet
    silver_path: data/silver/erp/kitchen_logs.parquet
    dq_threshold: 5  