domain: FACT

tables:
  fact_sales:
    silver_path:
      kitchen_logs: data/silver/crm/kitchen_logs.parquet
      order_items: data/silver/crm/order_items.parquet
      orders: data/silver/crm/orders.parquet
      delivery_logs: data/silver/crm/delivery_logs.parquet

    gold_path: data/gold/fact_sales.parquet

    dim_path:
      customers: data/gold/dim_customers.parquet
      restaurants: data/gold/dim_restaurants.parquet
      menu_items: data/gold/dim_menu_items.parquet
      delivery_partners: data/gold/dim_delivery_partners.parquet
